import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from './QueryProvider';
import { useState } from 'react';
import { Button } from '@/components/ui/button';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Import SidebarLayout dynamically to keep this a server component
  const SidebarLayout = require('./SidebarLayout').default;
  return (
    <html lang="en">
      <head>
        <link href="https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700&display=swap" rel="stylesheet" />
        <link rel="icon" type="image/png" href="/favicon-32x32.png" />
      </head>
      <body className="font-satoshi bg-background text-primary min-h-screen px-0 py-0">
        <QueryProvider>
          <SidebarLayout>
            {children}
          </SidebarLayout>
        </QueryProvider>
      </body>
    </html>
  );
}
